In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

sns.set_style("darkgrid")
# Set the random seed for reproducibility
np.random.seed(0)

In [3]:
df = pd.read_csv('../4_Data_for_predictions/LOCFnB_Andhra_Pradesh.csv', index_col= 'datetime')
df.index = pd.to_datetime(df.index)
df.head(3)

,PM10 (ug/m3),NOx (ppb),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),Benzene (ug/m3),Toluene (ug/m3),Temp (degree C),RH (%),WS (m/s),SR (W/mt2),BP (mmHg),VWS (m/s),Xylene (ug/m3),RF (mm),AT (degree C),WD (degree)
datetime,,,,,,,,,,,,,,,,,,
2016-07-01 10:00:00,39.0,32.33,7.07,6.6,0.48,14.5,1.0,4.63,33.43,71.67,2.3,123.67,925.25,-0.1,0.1,0.0,23.05,226.33
2016-07-01 11:00:00,39.0,35.80,7.40,6.6,0.49,15.0,0.7,4.50,33.70,70.00,2.5,186.00,925.25,-0.1,0.1,0.0,23.05,223.00
2016-07-01 12:00:00,39.0,35.80,7.40,6.6,0.49,15.0,0.7,4.50,33.70,70.00,2.5,186.00,925.25,-0.1,0.1,0.0,23.05,223.00

In [ ]:
target = 'PM10 (ug/m3)'